apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricradio-zookeeper-deployment
  labels:
    app: cricradio-zookeeper-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cricradio-zookeeper
  
  template:
    meatadata:
      labels:
        app: cricradio-zookeeper
    spec:
      containers:
      - name: cricradio-zookeeper
        image: confluentinc/cp-zookeeper:4.1.1
        ports:
          containerPort: 32181
        env:
        - ZOOKEEPER_CLIENT_PORT: 32181
        - ZOOKEEPER_TICK_TIME: 2000
        - ZOOKEEPER_SYNC_LIMIT: 2