apiVersion: v1
kind: Service
metadata:
  name: cricradio-kafka-service
spec:
  selector:
    app: cricradio-kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 29092
      targetPort: 29092
    
    - name: kafka-rest
      protocol: TCP
      port: 39092
      targetPort: 39092
    
    - name: go
      protocol: TCP
      port: 9092
      targetPort: 9092