name: Kubescape scanning for misconfigurations
on: push
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Add Security
        title: Auto Fixed by Kubescape.
        branch: kubescape-auto-fix-${{ github.head_ref }} 
